version: "3.3"

services:
  db:
    container_name: "utk-am-db"
    image: "mariadb:latest"
    volumes:
      - "./db:/var/lib/mysql"
    ports:
      - "18766:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password

  phpmyadmin:
    container_name: "utk-am-phpmyadmin"
    image: "phpmyadmin/phpmyadmin"
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

  wp:
    container_name: "utk-am-wp"
    image: "wordpress:latest"
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
      #WORDPRESS_DEBUG: 1
    volumes:
      - "./wp:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"

volumes:
  utk-am-db: { }
  utk-am-wp: { }